"""Rules-based fallback for brief generation when Claude is unavailable.

Generates deterministic briefs based on KPI comparisons and schedule analysis.
"""

import logging
from datetime import datetime
from typing import Any

logger = logging.getLogger(__name__)


def generate_rules_brief(
    kpis_baseline: dict[str, Any],
    kpis_optimized: dict[str, Any],
    schedule_baseline: list[dict],
    schedule_optimized: list[dict],
    scenario_meta: dict[str, Any],
) -> dict[str, Any]:
    """Generate a planner brief using rules-based logic.
    
    Args:
        kpis_baseline: Baseline schedule KPIs
        kpis_optimized: Optimized schedule KPIs
        schedule_baseline: Baseline schedule operations
        schedule_optimized: Optimized schedule operations
        scenario_meta: Scenario metadata (orders, machines, etc.)
        
    Returns:
        Brief content dictionary
    """
    # Calculate KPI deltas
    kpi_deltas = _calculate_kpi_deltas(kpis_baseline, kpis_optimized)
    
    # Generate summary
    summary = _generate_summary(kpi_deltas, scenario_meta)
    
    # Generate recommendations
    recommendations = _generate_recommendations(
        kpi_deltas, kpis_optimized, schedule_optimized, scenario_meta
    )
    
    # Analyze bottleneck
    bottleneck_analysis = _analyze_bottleneck(
        kpis_baseline, kpis_optimized, schedule_optimized, scenario_meta
    )
    
    # Add limitations
    limitations = [
        "Analysis generated by rules-based system (Claude unavailable)",
        "Recommendations based on KPI comparisons only",
        "Deep semantic analysis not available in this mode",
    ]
    
    return {
        "summary": summary,
        "kpi_deltas": kpi_deltas,
        "recommendations": recommendations,
        "bottleneck_analysis": bottleneck_analysis,
        "limitations": limitations,
    }


def _calculate_kpi_deltas(
    baseline: dict[str, Any],
    optimized: dict[str, Any],
) -> list[dict[str, Any]]:
    """Calculate deltas between baseline and optimized KPIs."""
    deltas = []
    
    metrics_to_compare = [
        ("makespan", "Makespan (minutes)", True),  # lower is better
        ("on_time_delivery_pct", "On-Time Delivery (%)", False),  # higher is better
        ("machine_utilization_pct", "Machine Utilization (%)", False),  # higher is better
        ("total_setup_time", "Total Setup Time (minutes)", True),  # lower is better
        ("family_switches", "Family Switches", True),  # lower is better
    ]
    
    for metric, display_name, lower_is_better in metrics_to_compare:
        baseline_val = baseline.get(metric, 0)
        optimized_val = optimized.get(metric, 0)
        
        if baseline_val == 0:
            improvement_pct = 0
        elif lower_is_better:
            improvement_pct = ((baseline_val - optimized_val) / baseline_val) * 100
        else:
            improvement_pct = ((optimized_val - baseline_val) / baseline_val) * 100
        
        is_improvement = improvement_pct > 0
        
        deltas.append({
            "metric": metric,
            "baseline_value": baseline_val,
            "optimized_value": optimized_val,
            "improvement_pct": round(improvement_pct, 1),
            "is_improvement": is_improvement,
        })
    
    return deltas


def _generate_summary(
    kpi_deltas: list[dict[str, Any]],
    scenario_meta: dict[str, Any],
) -> str:
    """Generate executive summary text."""
    num_orders = scenario_meta.get("num_orders", 0)
    num_ops = scenario_meta.get("num_operations", 0)
    num_machines = scenario_meta.get("num_machines", 0)
    
    # Find most significant improvements
    improvements = [d for d in kpi_deltas if d["is_improvement"]]
    improvements.sort(key=lambda x: abs(x["improvement_pct"]), reverse=True)
    
    summary_parts = [
        f"Schedule optimization for {num_orders} orders ({num_ops} operations) "
        f"across {num_machines} machines.",
    ]
    
    if improvements:
        best = improvements[0]
        summary_parts.append(
            f" Key improvement: {best['metric'].replace('_', ' ').title()} "
            f"improved by {abs(best['improvement_pct']):.1f}%."
        )
    
    makespan_delta = next((d for d in kpi_deltas if d["metric"] == "makespan"), None)
    if makespan_delta:
        baseline_hrs = makespan_delta["baseline_value"] / 60
        optimized_hrs = makespan_delta["optimized_value"] / 60
        summary_parts.append(
            f" Makespan reduced from {baseline_hrs:.1f} hours to {optimized_hrs:.1f} hours."
        )
    
    return "".join(summary_parts)


def _generate_recommendations(
    kpi_deltas: list[dict[str, Any]],
    kpis_optimized: dict[str, Any],
    schedule_optimized: list[dict],
    scenario_meta: dict[str, Any],
) -> list[dict[str, Any]]:
    """Generate prioritized recommendations.
    
    IMPORTANT: Only references machine IDs that exist in scenario_meta.
    """
    recommendations = []
    priority = 1
    
    # Extract valid machine IDs from scenario_meta
    machines = scenario_meta.get("machines", [])
    valid_machine_ids = [m.get("machine_id") for m in machines if m.get("machine_id")]
    
    # Find machines with actual operations in schedule
    machines_in_schedule = list(set(
        op.get("machine_id") for op in schedule_optimized if op.get("machine_id")
    ))
    # Only include machines that are both in scenario and schedule
    relevant_machines = [m for m in machines_in_schedule if m in valid_machine_ids]
    
    # Find the bottleneck machine (highest utilization)
    machine_load: dict[str, int] = {}
    for op in schedule_optimized:
        mid = op.get("machine_id")
        dur = op.get("duration_min", 0)
        if mid and mid in valid_machine_ids:
            machine_load[mid] = machine_load.get(mid, 0) + dur
    
    bottleneck_machine = max(machine_load.keys(), key=lambda k: machine_load[k]) if machine_load else None
    
    # Check on-time delivery
    otd = next((d for d in kpi_deltas if d["metric"] == "on_time_delivery_pct"), None)
    if otd and otd["optimized_value"] < 100:
        late_orders = [
            op.get("order_id") 
            for op in schedule_optimized 
            if op.get("is_late", False)
        ]
        # Only include order IDs that are valid
        valid_orders = scenario_meta.get("orders", [])
        valid_order_ids = {o.get("order_id") for o in valid_orders if o.get("order_id")}
        late_orders = [oid for oid in late_orders if oid in valid_order_ids]
        
        recommendations.append({
            "priority": priority,
            "title": "Address Late Orders",
            "description": (
                f"On-time delivery is {otd['optimized_value']:.1f}%. "
                f"Review capacity for affected orders."
            ),
            "impact": "Improve customer satisfaction and reduce expediting costs",
            "related_orders": list(set(late_orders))[:5],
            "related_machines": [],
        })
        priority += 1
    
    # Check utilization
    util = next((d for d in kpi_deltas if d["metric"] == "machine_utilization_pct"), None)
    if util and util["optimized_value"] < 70:
        # Only include actual machines from scenario
        underutilized_machines = relevant_machines[:3] if relevant_machines else []
        recommendations.append({
            "priority": priority,
            "title": "Review Machine Utilization",
            "description": (
                f"Average utilization is {util['optimized_value']:.1f}%. "
                "Consider accepting additional work or reviewing shift patterns."
            ),
            "impact": "Increase throughput and reduce cost per part",
            "related_orders": [],
            "related_machines": underutilized_machines,
        })
        priority += 1
    
    # Check setup time
    setup = next((d for d in kpi_deltas if d["metric"] == "total_setup_time"), None)
    if setup and setup["is_improvement"] and abs(setup["improvement_pct"]) > 10:
        # Reference the actual bottleneck machine, not hardcoded
        bottleneck_ref = bottleneck_machine if bottleneck_machine else "the bottleneck machine"
        recommendations.append({
            "priority": priority,
            "title": "Setup Time Optimization Success",
            "description": (
                f"Setup time reduced by {abs(setup['improvement_pct']):.1f}%. "
                f"Continue grouping similar families on {bottleneck_ref}."
            ),
            "impact": "Maintain gains by preserving family grouping in scheduling",
            "related_orders": [],
            "related_machines": [bottleneck_machine] if bottleneck_machine else [],
        })
        priority += 1
    
    # Generic recommendation if none generated
    if not recommendations:
        recommendations.append({
            "priority": 1,
            "title": "Schedule Optimized",
            "description": "The optimized schedule meets current targets. No immediate actions required.",
            "impact": "Maintain current scheduling approach",
            "related_orders": [],
            "related_machines": [],
        })
    
    return recommendations


def _analyze_bottleneck(
    kpis_baseline: dict[str, Any],
    kpis_optimized: dict[str, Any],
    schedule_optimized: list[dict],
    scenario_meta: dict[str, Any] = None,
) -> str:
    """Analyze bottleneck machine performance.
    
    Dynamically identifies the bottleneck from schedule data.
    """
    # Calculate load per machine from schedule
    machine_load: dict[str, int] = {}
    machine_ops: dict[str, list] = {}
    
    for op in schedule_optimized:
        mid = op.get("machine_id")
        dur = op.get("duration_min", 0)
        if mid:
            machine_load[mid] = machine_load.get(mid, 0) + dur
            if mid not in machine_ops:
                machine_ops[mid] = []
            machine_ops[mid].append(op)
    
    if not machine_load:
        return "No machine operations found in schedule to analyze."
    
    # Find actual bottleneck (highest total work time)
    bottleneck_id = max(machine_load.keys(), key=lambda k: machine_load[k])
    bottleneck_ops = machine_ops.get(bottleneck_id, [])
    total_duration = machine_load[bottleneck_id]
    
    # Check family switches on bottleneck
    families_seen = []
    switches = 0
    for op in sorted(bottleneck_ops, key=lambda x: x.get("start_min", 0)):
        family = op.get("family_id")
        if family and families_seen and families_seen[-1] != family:
            switches += 1
        if family:
            families_seen.append(family)
    
    return (
        f"Bottleneck machine {bottleneck_id} has {len(bottleneck_ops)} operations with "
        f"{total_duration:.0f} minutes of work. "
        f"Family switches: {switches}. "
        "Optimization reduces setup time by grouping similar part families."
    )


def answer_why_question_rules(
    question: str,
    schedule_optimized: list[dict],
    scenario_meta: dict[str, Any],
) -> dict[str, Any]:
    """Answer a 'why' question using rules-based logic.
    
    IMPORTANT: Only references machine/order IDs that exist in scenario_meta.
    
    Args:
        question: The question to answer
        schedule_optimized: Optimized schedule
        scenario_meta: Scenario metadata
        
    Returns:
        Answer dictionary with evidence
    """
    question_lower = question.lower()
    
    # Extract valid IDs from scenario_meta
    orders = scenario_meta.get("orders", [])
    machines = scenario_meta.get("machines", [])
    valid_order_ids = [o.get("order_id") for o in orders if o.get("order_id")]
    valid_machine_ids = [m.get("machine_id") for m in machines if m.get("machine_id")]
    
    # Look for order-specific questions using actual order IDs
    mentioned_orders = [oid for oid in valid_order_ids if oid and oid.lower() in question_lower]
    
    # Look for machine-specific questions using actual machine IDs
    mentioned_machines = [mid for mid in valid_machine_ids if mid and mid.lower() in question_lower]
    
    # Find bottleneck dynamically
    machine_load: dict[str, int] = {}
    for op in schedule_optimized:
        mid = op.get("machine_id")
        dur = op.get("duration_min", 0)
        if mid:
            machine_load[mid] = machine_load.get(mid, 0) + dur
    
    bottleneck_id = max(machine_load.keys(), key=lambda k: machine_load[k]) if machine_load else None
    
    # Generate answer based on question type
    if "late" in question_lower or "delay" in question_lower:
        answer = _answer_lateness_question(schedule_optimized, mentioned_orders)
    elif "setup" in question_lower or "changeover" in question_lower:
        answer = _answer_setup_question(schedule_optimized, scenario_meta, bottleneck_id)
    elif "bottleneck" in question_lower or (bottleneck_id and bottleneck_id.lower() in question_lower):
        answer = _answer_bottleneck_question(schedule_optimized, scenario_meta, bottleneck_id)
    elif "utilization" in question_lower:
        answer = _answer_utilization_question(schedule_optimized, scenario_meta)
    else:
        # Generic answer - reference actual bottleneck if known
        bottleneck_ref = bottleneck_id if bottleneck_id else "the bottleneck machine"
        answer = {
            "text": (
                "Based on the optimization results, the schedule minimizes makespan "
                "while respecting machine capacity, precedence constraints, and "
                f"sequence-dependent setup times on {bottleneck_ref}."
            ),
            "evidence": [
                "CP-SAT solver optimizes for minimum makespan",
                "NoOverlap constraints ensure machine capacity",
                "AddCircuit models setup time transitions",
            ],
        }
    
    return {
        "answer": answer["text"],
        "evidence": answer["evidence"],
        "related_operations": mentioned_orders,
    }


def _answer_lateness_question(
    schedule: list[dict],
    orders: list[str],
) -> dict[str, Any]:
    """Answer a question about late orders."""
    late_ops = [op for op in schedule if op.get("is_late", False)]
    
    if not late_ops:
        return {
            "text": "All orders are scheduled to complete on time.",
            "evidence": ["No operations exceed their due dates in the optimized schedule"],
        }
    
    return {
        "text": (
            f"There are {len(late_ops)} late operations. "
            "Potential causes: high workload, long setup times, or tight due dates. "
            "Consider capacity increases or due date negotiation."
        ),
        "evidence": [
            f"{len(late_ops)} operations complete after due date",
            "Solver minimizes makespan but cannot always meet all due dates",
        ],
    }


def _answer_setup_question(
    schedule: list[dict],
    scenario_meta: dict[str, Any],
    bottleneck_id: str = None,
) -> dict[str, Any]:
    """Answer a question about setup times.
    
    Uses actual machine IDs from scenario, not hardcoded.
    """
    # Use actual bottleneck or find one
    if not bottleneck_id:
        machine_load: dict[str, int] = {}
        for op in schedule:
            mid = op.get("machine_id")
            dur = op.get("duration_min", 0)
            if mid:
                machine_load[mid] = machine_load.get(mid, 0) + dur
        bottleneck_id = max(machine_load.keys(), key=lambda k: machine_load[k]) if machine_load else "the bottleneck"
    
    bottleneck_ops = [op for op in schedule if op.get("machine_id") == bottleneck_id]
    
    return {
        "text": (
            f"Setup times on {bottleneck_id} are sequence-dependent and vary by part family. "
            "The solver groups similar families together when possible to minimize "
            "total setup time while still meeting due dates."
        ),
        "evidence": [
            "AddCircuit constraint models setup transitions",
            "Family grouping reduces changeovers",
            f"{len(bottleneck_ops)} operations scheduled on {bottleneck_id}",
        ],
    }


def _answer_bottleneck_question(
    schedule: list[dict],
    scenario_meta: dict[str, Any],
    bottleneck_id: str = None,
) -> dict[str, Any]:
    """Answer a question about the bottleneck machine.
    
    Uses actual machine IDs from scenario, not hardcoded.
    """
    # Use actual bottleneck or find one
    if not bottleneck_id:
        machine_load: dict[str, int] = {}
        for op in schedule:
            mid = op.get("machine_id")
            dur = op.get("duration_min", 0)
            if mid:
                machine_load[mid] = machine_load.get(mid, 0) + dur
        bottleneck_id = max(machine_load.keys(), key=lambda k: machine_load[k]) if machine_load else "unknown"
    
    bottleneck_ops = [op for op in schedule if op.get("machine_id") == bottleneck_id]
    total_time = sum(op.get("duration_min", 0) for op in bottleneck_ops)
    
    return {
        "text": (
            f"{bottleneck_id} is the bottleneck with {len(bottleneck_ops)} operations totaling "
            f"{total_time:.0f} minutes. It has sequence-dependent setup times "
            "that the optimizer minimizes through family grouping."
        ),
        "evidence": [
            f"{bottleneck_id} has highest utilization",
            "Setup times vary by part family transition",
            f"Optimization focuses on {bottleneck_id} sequencing",
        ],
    }


def _answer_utilization_question(
    schedule: list[dict],
    scenario_meta: dict[str, Any],
) -> dict[str, Any]:
    """Answer a question about utilization."""
    machines = scenario_meta.get("machines", [])
    
    return {
        "text": (
            f"Utilization varies across {len(machines)} machines based on "
            "workload distribution and machine-specific capabilities. "
            "The optimizer assigns operations to minimize total makespan."
        ),
        "evidence": [
            "Operations assigned based on routing requirements",
            "Machine availability windows constrain scheduling",
            "Makespan minimization drives assignment",
        ],
    }
